// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_on_data_providers
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANUtQmo49FcMKwnC1O8dVrP2l0Gt-aC1w',
    appId: '1:1088041065522:web:0681556b9989349521f02b',
    messagingSenderId: '1088041065522',
    projectId: 'streaksky-dev',
    authDomain: 'streaksky-dev.firebaseapp.com',
    storageBucket: 'streaksky-dev.firebasestorage.app',
    measurementId: 'G-K6L0RCYCZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI9wrTateK1PM_R1tJ_KXIKrGjLmtkmiU',
    appId: '1:1088041065522:android:2b44016f0e637d9d21f02b',
    messagingSenderId: '1088041065522',
    projectId: 'streaksky-dev',
    storageBucket: 'streaksky-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANUtQmo49FcMKwnC1O8dVrP2l0Gt-aC1w',
    appId: 'YOUR-APP-ID', // TODO: Update this for iOS
    messagingSenderId: '1088041065522',
    projectId: 'streaksky-dev',
    storageBucket: 'streaksky-dev.firebasestorage.app',
    iosBundleId: 'com.example.streaksky',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANUtQmo49FcMKwnC1O8dVrP2l0Gt-aC1w',
    appId: 'YOUR-APP-ID', // TODO: Update this for macOS
    messagingSenderId: '1088041065522',
    projectId: 'streaksky-dev',
    storageBucket: 'streaksky-dev.firebasestorage.app',
    iosBundleId: 'com.example.streaksky',
  );
}
